name: Expo - CI & CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  credentials:
    name: Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Show Credentials
        run: echo "${{ secrets.EXPO_TOKEN }}"

  deployment:
    name: Expo Deployment
    uses: ./.github/workflows/expo-deployment.yml
    with:
      environment: staging
      expo-token: ${{ secrets.EXPO_TOKEN }}
    needs: credentials
