name: Expo - CI & CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  deployment:
    name: Expo Deployment
    uses: ./.github/workflows/expo-deployment.yml
    with:
      environment: staging
      expo-token: ${{ env.EXPO_TOKEN }}
