on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  expo-staging-deployment:
    name: Staging - Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Display secrets
        run: echo "${{ secrets.EXPO_TOKEN }}"

      - name: Create android apk preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas build --profile preview --platform android
